/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_v1_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_import_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_v1_import_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Preset */
        delete: operations["delete_preset_api_v1_import_presets__preset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_imports_get"];
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_imports__batch_id__get"];
        put?: never;
        post?: never;
        /**
         * Undo
         * @description Discard a preview, or undo a committed import: all its transactions are removed.
         */
        delete: operations["undo_api_v1_imports__batch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{batch_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit */
        post: operations["commit_api_v1_imports__batch_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{batch_id}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dry Run */
        get: operations["dry_run_api_v1_imports__batch_id__dry_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{batch_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Mapping
         * @description Save the column mapping and return the dry run: what would be imported, nothing written.
         */
        put: operations["set_mapping_api_v1_imports__batch_id__mapping_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_api_v1_instruments_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve */
        get: operations["resolve_api_v1_instruments_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_instruments__instrument_id__delete"];
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch_api_v1_instruments__instrument_id__patch"];
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prices */
        get: operations["prices_api_v1_instruments__instrument_id__prices_get"];
        put?: never;
        /**
         * Set Price
         * @description Enter or override one close by hand; audited and protected from later fetches.
         */
        post: operations["set_price_api_v1_instruments__instrument_id__prices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position Detail */
        get: operations["position_detail_api_v1_positions__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Section */
        get: operations["get_section_api_v1_settings__section__get"];
        /** Put Section */
        put: operations["put_section_api_v1_settings__section__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create First Account */
        post: operations["create_first_account_api_v1_setup_account_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete_api_v1_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Owner
         * @description First-run only: there is exactly one owner and no other way to create accounts.
         */
        post: operations["create_owner_api_v1_setup_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/fx-prefill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fx Prefill
         * @description The ECB rate the form prefills for a trade date (the owner can overwrite it).
         */
        get: operations["fx_prefill_api_v1_transactions_fx_prefill_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/preview-sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Sell
         * @description Shows the lots a sell would consume and the realized result before anything is saved.
         */
        post: operations["preview_sell_api_v1_transactions_preview_sell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up and serving.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: the database answers and its schema is at the latest migration.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountChanges */
        AccountChanges: {
            /** Active */
            active?: boolean | null;
            /** Broker */
            broker?: string | null;
            /** Cost Basis Method */
            cost_basis_method?: ("FIFO" | "AVG") | null;
            /** Name */
            name?: string | null;
        };
        /** BatchOut */
        BatchOut: {
            /** Account Id */
            account_id: number;
            /** Committed At */
            committed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** File Name */
            file_name: string;
            /** Id */
            id: number;
            /** Preset Id */
            preset_id: number | null;
            /** Rows Imported */
            rows_imported: number;
            /** Rows Skipped */
            rows_skipped: number;
            /** Rows Total */
            rows_total: number;
            /** Status */
            status: string;
        };
        /** Body_upload_api_v1_imports_post */
        Body_upload_api_v1_imports_post: {
            /** Account Id */
            account_id: number;
            /** File */
            file: string;
            /** Preset Id */
            preset_id?: number | null;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Confirmed By */
            confirmed_by: string | null;
            /** Currency */
            currency: string;
            /** Currency Confirmed */
            currency_confirmed: boolean;
            /** Exchange Name */
            exchange_name: string;
            /** Mic */
            mic: string;
            /** Ticker */
            ticker: string;
            /** Usable */
            usable: boolean;
            /** Warning */
            warning: string | null;
        };
        /** CommitIn */
        CommitIn: {
            /**
             * Skip Errors
             * @default false
             */
            skip_errors: boolean;
        };
        /** DryRunOut */
        DryRunOut: {
            /** Batch Id */
            batch_id: number;
            /** Can Commit */
            can_commit: boolean;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Rows */
            rows: components["schemas"]["RowOut"][];
            /** Truncated */
            truncated: boolean;
            /** Unknown Isins */
            unknown_isins: string[];
        };
        /** FxPrefillOut */
        FxPrefillOut: {
            /** Currency */
            currency: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Fx Rate To Eur */
            fx_rate_to_eur: string;
            /**
             * Rate Date
             * Format: date
             */
            rate_date: string;
            /** Rate Per Eur */
            rate_per_eur: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeaderOut */
        HeaderOut: {
            /** Index */
            index: number;
            /** Label */
            label: string;
        };
        /**
         * ImportMapping
         * @description Everything needed to read one export layout; saved as a preset (FR-TX-07).
         */
        ImportMapping: {
            /** Amount Col */
            amount_col?: number | null;
            /** Currency Col */
            currency_col?: number | null;
            /** Date Col */
            date_col?: number | null;
            /**
             * Date Format
             * @default %d-%m-%Y
             */
            date_format: string;
            /**
             * Decimal Separator
             * @default .
             * @enum {string}
             */
            decimal_separator: "," | ".";
            /** Default Currency */
            default_currency?: string | null;
            /** Fees Col */
            fees_col?: number | null;
            /** Fees Currency Col */
            fees_currency_col?: number | null;
            /** Fx Col */
            fx_col?: number | null;
            /**
             * Fx Semantics
             * @default per_eur
             * @enum {string}
             */
            fx_semantics: "per_eur" | "to_eur";
            /** Isin Col */
            isin_col?: number | null;
            /** Note Col */
            note_col?: number | null;
            /** Price Col */
            price_col?: number | null;
            /** Quantity Col */
            quantity_col?: number | null;
            /** Reference Col */
            reference_col?: number | null;
            /** Skip Types */
            skip_types?: string[];
            /**
             * Thousands Separator
             * @default
             * @enum {string}
             */
            thousands_separator: "" | "." | "," | " ";
            /** Time Col */
            time_col?: number | null;
            /** Type Col */
            type_col?: number | null;
            /** Type Map */
            type_map?: {
                [key: string]: string;
            };
            /**
             * Type Mode
             * @default sign
             * @enum {string}
             */
            type_mode: "sign" | "column";
        };
        /** InstrumentChanges */
        InstrumentChanges: {
            /** Asset Class */
            asset_class?: ("ETF" | "ETC" | "EQUITY" | "BOND" | "FUND" | "CASH" | "OTHER") | null;
            /** Coupon Pct */
            coupon_pct?: number | string | null;
            /** Distribution */
            distribution?: ("ACC" | "DIST") | null;
            /** Domicile */
            domicile?: string | null;
            /** Issuer */
            issuer?: string | null;
            /** Maturity Date */
            maturity_date?: string | null;
            /** Name */
            name?: string | null;
            /** Rating */
            rating?: string | null;
            /** Status */
            status?: ("active" | "archived") | null;
            /** Tags */
            tags?: string[] | null;
            /** Ter Pct */
            ter_pct?: number | string | null;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Asset Class */
            asset_class: string;
            /** Coupon Pct */
            coupon_pct: string | null;
            /** Distribution */
            distribution: string | null;
            /** Domicile */
            domicile: string | null;
            /** Id */
            id: number;
            /** Isin */
            isin: string | null;
            /** Issuer */
            issuer: string | null;
            last_close: components["schemas"]["LastClose"] | null;
            /** Listings */
            listings: components["schemas"]["ListingOut"][];
            /** Manual */
            manual: boolean;
            /** Maturity Date */
            maturity_date: string | null;
            /** Name */
            name: string;
            /** Rating */
            rating: string | null;
            /** Stale */
            stale: boolean;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /** Ter Pct */
            ter_pct: string | null;
        };
        /** InstrumentRef */
        InstrumentRef: {
            /** Asset Class */
            asset_class: string;
            /** Currency */
            currency: string | null;
            /** Id */
            id: number;
            /** Isin */
            isin: string | null;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string | null;
        };
        /** LastClose */
        LastClose: {
            /** Close */
            close: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Overridden */
            overridden: boolean;
            /** Source */
            source: string;
        };
        /** ListingChoice */
        ListingChoice: {
            /** Currency */
            currency: string;
            /** Mic */
            mic: string;
            /** Ticker */
            ticker: string;
        };
        /** ListingOut */
        ListingOut: {
            /** Currency */
            currency: string;
            /** Id */
            id: number;
            /** Mic */
            mic: string;
            /** Primary */
            primary: boolean;
            /** Provider Symbols */
            provider_symbols: {
                [key: string]: string;
            };
            /** Ticker */
            ticker: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /**
             * Remember
             * @default false
             */
            remember: boolean;
            /** Username */
            username: string;
        };
        /** LotOut */
        LotOut: {
            /** Account Id */
            account_id: number;
            /** Avg Cost Eur */
            avg_cost_eur: string;
            /** Buy Transaction Id */
            buy_transaction_id: number;
            /** Cost Eur */
            cost_eur: string;
            /** Market Value Eur */
            market_value_eur: string | null;
            /** Open Quantity */
            open_quantity: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Unrealized Pnl Eur */
            unrealized_pnl_eur: string | null;
            /** Unrealized Ratio */
            unrealized_ratio: string | null;
        };
        /** ManualPriceIn */
        ManualPriceIn: {
            /** Close */
            close: number | string;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** MappingIn */
        MappingIn: {
            mapping: components["schemas"]["ImportMapping"];
            /** Save As Preset */
            save_as_preset?: string | null;
        };
        /** MeOut */
        MeOut: {
            /** Username */
            username: string;
        };
        /** NewInstrument */
        NewInstrument: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "ETF" | "ETC" | "EQUITY" | "BOND" | "FUND" | "CASH" | "OTHER";
            /** Coupon Pct */
            coupon_pct?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Distribution */
            distribution?: ("ACC" | "DIST") | null;
            /** Domicile */
            domicile?: string | null;
            /** Isin */
            isin?: string | null;
            /** Issuer */
            issuer?: string | null;
            listing?: components["schemas"]["ListingChoice"] | null;
            /**
             * Manual
             * @default false
             */
            manual: boolean;
            /** Maturity Date */
            maturity_date?: string | null;
            /** Name */
            name: string;
            /** Rating */
            rating?: string | null;
            /** Tags */
            tags?: string[];
            /** Ter Pct */
            ter_pct?: number | string | null;
        };
        /** OwnerIn */
        OwnerIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** PositionDetailOut */
        PositionDetailOut: {
            /** Account Id */
            account_id: number | null;
            /** As Of */
            as_of: string | null;
            instrument: components["schemas"]["InstrumentRef"];
            /** Lots */
            lots: components["schemas"]["LotOut"][];
            /** Matches */
            matches: components["schemas"]["folio__api__routers__positions__MatchOut"][];
            summary: components["schemas"]["PositionMetricsOut"];
            /** Transactions */
            transactions: components["schemas"]["TransactionOut"][];
        };
        /** PositionMetricsOut */
        PositionMetricsOut: {
            /** Avg Cost Eur */
            avg_cost_eur: string | null;
            /** Cost Basis Eur */
            cost_basis_eur: string;
            /** Cost Basis Native */
            cost_basis_native: string;
            /** Day Change Eur */
            day_change_eur: string | null;
            /** Day Change Ratio */
            day_change_ratio: string | null;
            /** First Trade Date */
            first_trade_date: string | null;
            /** Income Eur */
            income_eur: string;
            /** Market Value Eur */
            market_value_eur: string | null;
            /** Market Value Native */
            market_value_native: string | null;
            /** Note */
            note: string | null;
            price: components["schemas"]["folio__api__routers__positions__PriceOut"] | null;
            /** Quantity */
            quantity: string;
            /** Realized Pnl Eur */
            realized_pnl_eur: string;
            /** Total Return Eur */
            total_return_eur: string | null;
            /** Total Return Ratio */
            total_return_ratio: string | null;
            /** Unrealized Pnl Eur */
            unrealized_pnl_eur: string | null;
            /** Unrealized Pnl Native */
            unrealized_pnl_native: string | null;
            /** Unrealized Ratio */
            unrealized_ratio: string | null;
            /** Weight */
            weight: string | null;
        };
        /** PositionOut */
        PositionOut: {
            /** Account Id */
            account_id: number;
            /** Account Name */
            account_name: string;
            /** Asset Class */
            asset_class: string;
            /** Avg Cost Eur */
            avg_cost_eur: string | null;
            /** Cost Basis Eur */
            cost_basis_eur: string;
            /** Cost Basis Native */
            cost_basis_native: string;
            /** Currency */
            currency: string | null;
            /** Day Change Eur */
            day_change_eur: string | null;
            /** Day Change Ratio */
            day_change_ratio: string | null;
            /** First Trade Date */
            first_trade_date: string | null;
            /** Income Eur */
            income_eur: string;
            /** Instrument Id */
            instrument_id: number;
            /** Isin */
            isin: string | null;
            /** Market Value Eur */
            market_value_eur: string | null;
            /** Market Value Native */
            market_value_native: string | null;
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            price: components["schemas"]["folio__api__routers__positions__PriceOut"] | null;
            /** Quantity */
            quantity: string;
            /** Realized Pnl Eur */
            realized_pnl_eur: string;
            /** Ticker */
            ticker: string | null;
            /** Total Return Eur */
            total_return_eur: string | null;
            /** Total Return Ratio */
            total_return_ratio: string | null;
            /** Unrealized Pnl Eur */
            unrealized_pnl_eur: string | null;
            /** Unrealized Pnl Native */
            unrealized_pnl_native: string | null;
            /** Unrealized Ratio */
            unrealized_ratio: string | null;
            /** Weight */
            weight: string | null;
        };
        /** PositionsOut */
        PositionsOut: {
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            totals: components["schemas"]["TotalsOut"];
        };
        /** PresetIn */
        PresetIn: {
            mapping: components["schemas"]["ImportMapping"];
            /** Name */
            name: string;
        };
        /** PresetOut */
        PresetOut: {
            /** Id */
            id: number;
            mapping: components["schemas"]["ImportMapping"];
            /** Name */
            name: string;
        };
        /** PreviewOut */
        PreviewOut: {
            batch: components["schemas"]["BatchOut"];
            /** Delimiter */
            delimiter: string;
            /** Encoding */
            encoding: string;
            /** From Preset */
            from_preset: boolean;
            /** Headers */
            headers: components["schemas"]["HeaderOut"][];
            mapping: components["schemas"]["ImportMapping"];
            /** Row Count */
            row_count: number;
            /** Sample Rows */
            sample_rows: string[][];
        };
        /** ResolutionOut */
        ResolutionOut: {
            /** Asset Class */
            asset_class: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
            /** Domicile */
            domicile: string;
            /** Isin */
            isin: string;
            /** Issuer */
            issuer: string | null;
            /** Name */
            name: string;
        };
        /** RowOut */
        RowOut: {
            /** Reason */
            reason: string | null;
            /** Row */
            row: number;
            /** Status */
            status: string;
            /** Summary */
            summary: {
                [key: string]: string;
            } | null;
        };
        /** SellPreviewOut */
        SellPreviewOut: {
            /** Cost Eur */
            cost_eur: string;
            /** Matches */
            matches: components["schemas"]["folio__api__routers__transactions__MatchOut"][];
            /** Net Proceeds Eur */
            net_proceeds_eur: string;
            /** Realized Pct */
            realized_pct: string | null;
            /** Realized Pnl Eur */
            realized_pnl_eur: string;
            /** Remaining Cost Basis Eur */
            remaining_cost_basis_eur: string;
            /** Remaining Quantity */
            remaining_quantity: string;
        };
        /** SetupStatus */
        SetupStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Has Account */
            has_account: boolean;
            /** Needs Owner */
            needs_owner: boolean;
            /** Setup Complete */
            setup_complete: boolean;
        };
        /** TotalsOut */
        TotalsOut: {
            /** Cost Basis Eur */
            cost_basis_eur: string;
            /** Day Change Eur */
            day_change_eur: string | null;
            /** Income Eur */
            income_eur: string;
            /** Market Value Eur */
            market_value_eur: string;
            /** Positions */
            positions: number;
            /** Realized Pnl Eur */
            realized_pnl_eur: string;
            /** Unrealized Pnl Eur */
            unrealized_pnl_eur: string;
            /** Unrealized Ratio */
            unrealized_ratio: string | null;
            /** Unvalued Positions */
            unvalued_positions: number;
        };
        /**
         * TransactionChanges
         * @description Any subset of the input fields; the merged result is validated again.
         */
        TransactionChanges: {
            /** Currency */
            currency?: string | null;
            /** Fees */
            fees?: number | string | null;
            /** Fees Currency */
            fees_currency?: string | null;
            /** Fees Fx Rate To Eur */
            fees_fx_rate_to_eur?: number | string | null;
            /** Fx Rate To Eur */
            fx_rate_to_eur?: number | string | null;
            /** Instrument Id */
            instrument_id?: number | null;
            /** Net Amount Eur */
            net_amount_eur?: number | string | null;
            /** Note */
            note?: string | null;
            /** Price */
            price?: number | string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Ratio */
            ratio?: number | string | null;
            /** Settle Date */
            settle_date?: string | null;
            /** Taxes */
            taxes?: number | string | null;
            /** Taxes Currency */
            taxes_currency?: string | null;
            /** Taxes Fx Rate To Eur */
            taxes_fx_rate_to_eur?: number | string | null;
            /** Trade Date */
            trade_date?: string | null;
        };
        /** TransactionIn */
        TransactionIn: {
            /** Account Id */
            account_id: number;
            /** Currency */
            currency?: string | null;
            /**
             * Fees
             * @default 0
             */
            fees: number | string;
            /** Fees Currency */
            fees_currency?: string | null;
            /** Fees Fx Rate To Eur */
            fees_fx_rate_to_eur?: number | string | null;
            /** Fx Rate To Eur */
            fx_rate_to_eur?: number | string | null;
            /** Instrument Id */
            instrument_id?: number | null;
            /** Net Amount Eur */
            net_amount_eur?: number | string | null;
            /** Note */
            note?: string | null;
            /** Price */
            price?: number | string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Ratio */
            ratio?: number | string | null;
            /** Settle Date */
            settle_date?: string | null;
            /**
             * Taxes
             * @default 0
             */
            taxes: number | string;
            /** Taxes Currency */
            taxes_currency?: string | null;
            /** Taxes Fx Rate To Eur */
            taxes_fx_rate_to_eur?: number | string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /**
             * Type
             * @enum {string}
             */
            type: "buy" | "sell" | "dividend" | "interest" | "fee" | "tax" | "split" | "transfer_in" | "transfer_out" | "deposit" | "withdrawal";
        };
        /** TransactionOut */
        TransactionOut: {
            /** Account Id */
            account_id: number;
            /** Account Name */
            account_name: string;
            /** Currency */
            currency: string;
            /** External Ref */
            external_ref: string | null;
            /** Fees */
            fees: string;
            /** Fees Currency */
            fees_currency: string;
            /** Fees Fx Rate To Eur */
            fees_fx_rate_to_eur: string;
            /** Fx Rate To Eur */
            fx_rate_to_eur: string;
            /** Id */
            id: number;
            /** Import Batch Id */
            import_batch_id: number | null;
            /** Instrument Id */
            instrument_id: number | null;
            /** Instrument Name */
            instrument_name: string | null;
            /** Net Amount Eur */
            net_amount_eur: string | null;
            /** Note */
            note: string | null;
            /** Price */
            price: string;
            /** Quantity */
            quantity: string;
            /** Ratio */
            ratio: string | null;
            /** Settle Date */
            settle_date: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Taxes */
            taxes: string;
            /** Taxes Currency */
            taxes_currency: string;
            /** Taxes Fx Rate To Eur */
            taxes_fx_rate_to_eur: string;
            /** Ticker */
            ticker: string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Type */
            type: string;
        };
        /** TransactionPage */
        TransactionPage: {
            /** Items */
            items: components["schemas"]["TransactionOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** AccountIn */
        folio__api__routers__accounts__AccountIn: {
            /** Broker */
            broker?: string | null;
            /**
             * Cost Basis Method
             * @default FIFO
             * @enum {string}
             */
            cost_basis_method: "FIFO" | "AVG";
            /** Name */
            name: string;
        };
        /** AccountOut */
        folio__api__routers__accounts__AccountOut: {
            /** Active */
            active: boolean;
            /** Base Currency */
            base_currency: string;
            /** Broker */
            broker: string | null;
            /** Cost Basis Method */
            cost_basis_method: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Transaction Count */
            transaction_count: number;
        };
        /** PriceOut */
        folio__api__routers__instruments__PriceOut: {
            /** Close */
            close: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** High */
            high: string | null;
            /** Low */
            low: string | null;
            /** Open */
            open: string | null;
            /** Overridden */
            overridden: boolean;
            /** Source */
            source: string;
            /** Volume */
            volume: string | null;
        };
        /** MatchOut */
        folio__api__routers__positions__MatchOut: {
            /** Account Id */
            account_id: number;
            /** Cost Eur */
            cost_eur: string;
            /** Lot Buy Transaction Id */
            lot_buy_transaction_id: number;
            /** Proceeds Eur */
            proceeds_eur: string;
            /** Quantity */
            quantity: string;
            /** Realized Pnl Eur */
            realized_pnl_eur: string;
            /** Sell Date */
            sell_date: string | null;
            /** Sell Transaction Id */
            sell_transaction_id: number;
        };
        /** PriceOut */
        folio__api__routers__positions__PriceOut: {
            /** Close */
            close: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Overridden */
            overridden: boolean;
            /** Previous Close */
            previous_close: string | null;
            /** Source */
            source: string;
            /** Stale */
            stale: boolean;
        };
        /** AccountIn */
        folio__api__routers__setup__AccountIn: {
            /** Broker */
            broker?: string | null;
            /**
             * Cost Basis Method
             * @default FIFO
             * @enum {string}
             */
            cost_basis_method: "FIFO" | "AVG";
            /** Name */
            name: string;
        };
        /** AccountOut */
        folio__api__routers__setup__AccountOut: {
            /** Broker */
            broker: string | null;
            /** Cost Basis Method */
            cost_basis_method: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MatchOut */
        folio__api__routers__transactions__MatchOut: {
            /** Cost Eur */
            cost_eur: string;
            /** Lot Buy Transaction Id */
            lot_buy_transaction_id: number;
            /** Lot Trade Date */
            lot_trade_date: string | null;
            /** Proceeds Eur */
            proceeds_eur: string;
            /** Quantity */
            quantity: string;
            /** Realized Pnl Eur */
            realized_pnl_eur: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["folio__api__routers__accounts__AccountOut"][];
                };
            };
        };
    };
    create_account_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["folio__api__routers__accounts__AccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["folio__api__routers__accounts__AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_v1_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountChanges"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["folio__api__routers__accounts__AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_presets_api_v1_import_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"][];
                };
            };
        };
    };
    create_preset_api_v1_import_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preset_api_v1_import_presets__preset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"][];
                };
            };
        };
    };
    upload_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_imports__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_api_v1_imports__batch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_api_v1_imports__batch_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_api_v1_imports__batch_id__dry_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mapping_api_v1_imports__batch_id__mapping_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instruments_api_v1_instruments_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewInstrument"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_v1_instruments_resolve_get: {
        parameters: {
            query: {
                isin: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_instruments__instrument_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_api_v1_instruments__instrument_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentChanges"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prices_api_v1_instruments__instrument_id__prices_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["folio__api__routers__instruments__PriceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_price_api_v1_instruments__instrument_id__prices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPriceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["folio__api__routers__instruments__PriceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                account?: number | null;
                as_of?: string | null;
                include_closed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_detail_api_v1_positions__instrument_id__get: {
        parameters: {
            query?: {
                account?: number | null;
                as_of?: string | null;
            };
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_section_api_v1_settings__section__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_section_api_v1_settings__section__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_first_account_api_v1_setup_account_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["folio__api__routers__setup__AccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["folio__api__routers__setup__AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_api_v1_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_owner_api_v1_setup_owner_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query?: {
                account?: number | null;
                instrument?: number | null;
                type?: string | null;
                from?: string | null;
                to?: string | null;
                status?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fx_prefill_api_v1_transactions_fx_prefill_get: {
        parameters: {
            query: {
                currency: string;
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxPrefillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_sell_api_v1_transactions_preview_sell_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionChanges"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
