"""ledger and market data

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 21:43:05.042247
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rate",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate_per_eur", sa.String(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "currency"),
    )
    op.create_table(
        "import_preset",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "instrument",
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_class", sa.String(length=10), nullable=False),
        sa.Column("issuer", sa.String(length=100), nullable=True),
        sa.Column("domicile", sa.String(length=2), nullable=True),
        sa.Column("ter_pct", sa.String(), nullable=True),
        sa.Column("distribution", sa.String(length=4), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("coupon_pct", sa.String(), nullable=True),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("rating", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin"),
    )
    op.create_table(
        "job_request",
        sa.Column("job", sa.String(length=50), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("picked_up_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_request", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_request_status"), ["status"], unique=False)

    op.create_table(
        "job_run",
        sa.Column("job", sa.String(length=50), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("log", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_run_job"), ["job"], unique=False)

    op.create_table(
        "portfolio_snapshot",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_value_eur", sa.String(), nullable=False),
        sa.Column("net_contributions_eur", sa.String(), nullable=False),
        sa.Column("cash_eur", sa.String(), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.Column("is_peildatum", sa.Boolean(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "provider_call",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "day"),
    )
    op.create_table(
        "corporate_action",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("ratio", sa.String(), nullable=True),
        sa.Column("new_isin", sa.String(length=12), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "type", "ex_date"),
    )
    op.create_table(
        "import_batch",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("preset_id", sa.Integer(), nullable=True),
        sa.Column("rows_total", sa.Integer(), nullable=False),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("rows_skipped", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error_report", sa.JSON(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("committed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["import_preset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "listing",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("exchange_mic", sa.String(length=10), nullable=False),
        sa.Column("ticker", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider_symbols", sa.JSON(), nullable=False),
        sa.Column("pricing_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("listing", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listing_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "position",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.String(), nullable=False),
        sa.Column("cost_basis_eur", sa.String(), nullable=False),
        sa.Column("cost_basis_native", sa.String(), nullable=False),
        sa.Column("avg_cost_eur", sa.String(), nullable=True),
        sa.Column("realized_pnl_eur", sa.String(), nullable=False),
        sa.Column("income_eur", sa.String(), nullable=False),
        sa.Column("invested_eur", sa.String(), nullable=False),
        sa.Column("proceeds_eur", sa.String(), nullable=False),
        sa.Column("first_trade_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "instrument_id"),
    )
    op.create_table(
        "ledger_transaction",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=15), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("settle_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.String(), nullable=False),
        sa.Column("price", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate_to_eur", sa.String(), nullable=False),
        sa.Column("fees", sa.String(), nullable=False),
        sa.Column("fees_currency", sa.String(length=3), nullable=False),
        sa.Column("fees_fx_rate_to_eur", sa.String(), nullable=False),
        sa.Column("taxes", sa.String(), nullable=False),
        sa.Column("taxes_currency", sa.String(length=3), nullable=False),
        sa.Column("taxes_fx_rate_to_eur", sa.String(), nullable=False),
        sa.Column("net_amount_eur", sa.String(), nullable=True),
        sa.Column("ratio", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledger_transaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ledger_transaction_import_batch_id"), ["import_batch_id"], unique=False
        )
        batch_op.create_index(
            "ix_ledger_tx_account_instrument",
            ["account_id", "instrument_id", "trade_date"],
            unique=False,
        )
        batch_op.create_index(
            "uq_ledger_tx_external_ref",
            ["account_id", "external_ref"],
            unique=True,
            sqlite_where=sa.text("external_ref IS NOT NULL AND deleted_at IS NULL"),
        )

    op.create_table(
        "price_bar",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.String(), nullable=True),
        sa.Column("high", sa.String(), nullable=True),
        sa.Column("low", sa.String(), nullable=True),
        sa.Column("close", sa.String(), nullable=False),
        sa.Column("adj_close", sa.String(), nullable=True),
        sa.Column("volume", sa.String(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("overridden", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id", "date"),
    )
    op.create_table(
        "lot",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("buy_transaction_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open_quantity", sa.String(), nullable=False),
        sa.Column("cost_eur", sa.String(), nullable=False),
        sa.Column("cost_native", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["buy_transaction_id"],
            ["ledger_transaction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lot", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lot_account_instrument", ["account_id", "instrument_id"], unique=False
        )

    op.create_table(
        "lot_match",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("sell_transaction_id", sa.Integer(), nullable=False),
        sa.Column("lot_buy_transaction_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.String(), nullable=False),
        sa.Column("cost_eur", sa.String(), nullable=False),
        sa.Column("proceeds_eur", sa.String(), nullable=False),
        sa.Column("realized_pnl_eur", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lot_buy_transaction_id"],
            ["ledger_transaction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sell_transaction_id"],
            ["ledger_transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lot_match", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lot_match_sell_transaction_id"), ["sell_transaction_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lot_match", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lot_match_sell_transaction_id"))

    op.drop_table("lot_match")
    with op.batch_alter_table("lot", schema=None) as batch_op:
        batch_op.drop_index("ix_lot_account_instrument")

    op.drop_table("lot")
    op.drop_table("price_bar")
    with op.batch_alter_table("ledger_transaction", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_ledger_tx_external_ref",
            sqlite_where=sa.text("external_ref IS NOT NULL AND deleted_at IS NULL"),
        )
        batch_op.drop_index("ix_ledger_tx_account_instrument")
        batch_op.drop_index(batch_op.f("ix_ledger_transaction_import_batch_id"))

    op.drop_table("ledger_transaction")
    op.drop_table("position")
    with op.batch_alter_table("listing", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listing_instrument_id"))

    op.drop_table("listing")
    op.drop_table("import_batch")
    op.drop_table("corporate_action")
    op.drop_table("provider_call")
    op.drop_table("portfolio_snapshot")
    with op.batch_alter_table("job_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_run_job"))

    op.drop_table("job_run")
    with op.batch_alter_table("job_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_request_status"))

    op.drop_table("job_request")
    op.drop_table("instrument")
    op.drop_table("import_preset")
    op.drop_table("fx_rate")
    # ### end Alembic commands ###
