"""snapshot income costs

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 22:39:03.225627
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("portfolio_snapshot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("income_eur", sa.String(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("costs_eur", sa.String(), server_default="0", nullable=False))
        batch_op.add_column(
            sa.Column("unvalued_positions", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("portfolio_snapshot", schema=None) as batch_op:
        batch_op.drop_column("unvalued_positions")
        batch_op.drop_column("costs_eur")
        batch_op.drop_column("income_eur")

    # ### end Alembic commands ###
