"""strategies signals notifications

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 13:07:26.250194
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_version",
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("yaml", sa.Text(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id", "version"),
    )
    with op.batch_alter_table("strategy_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_strategy_version_strategy_id"), ["strategy_id"], unique=False
        )

    op.create_table(
        "price_alert",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(length=6), nullable=False),
        sa.Column("threshold", sa.String(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("armed", sa.Boolean(), nullable=False),
        sa.Column("last_fired_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price_alert", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_price_alert_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "signal",
        sa.Column("strategy_version_id", sa.Integer(), nullable=True),
        sa.Column("rule_id", sa.String(length=60), nullable=False),
        sa.Column("rule_type", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("shadow", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signal", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signal_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_signal_strategy_version_id"), ["strategy_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_signal_ts"), ["ts"], unique=False)

    op.create_table(
        "notification",
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("push_title", sa.String(length=200), nullable=False),
        sa.Column("push_body", sa.String(length=400), nullable=False),
        sa.Column("push_body_anonymous", sa.String(length=400), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_subject"), ["subject"], unique=False)

    op.create_table(
        "notification_delivery",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("merged_into_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_delivery", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_delivery_notification_id"),
            ["notification_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_delivery_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_delivery", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_delivery_status"))
        batch_op.drop_index(batch_op.f("ix_notification_delivery_notification_id"))

    op.drop_table("notification_delivery")
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_subject"))

    op.drop_table("notification")
    with op.batch_alter_table("signal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signal_ts"))
        batch_op.drop_index(batch_op.f("ix_signal_strategy_version_id"))
        batch_op.drop_index(batch_op.f("ix_signal_dedup_key"))

    op.drop_table("signal")
    with op.batch_alter_table("price_alert", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_alert_instrument_id"))

    op.drop_table("price_alert")
    with op.batch_alter_table("strategy_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_version_strategy_id"))

    op.drop_table("strategy_version")
    op.drop_table("strategy")
    # ### end Alembic commands ###
