"""lookthrough news agent

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 17:41:08.986200
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_run",
        sa.Column("trigger", sa.String(length=60), nullable=False),
        sa.Column("run_type", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("prompt_version", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("web_searches", sa.Integer(), nullable=False),
        sa.Column("cost_eur", sa.String(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("tool_calls", sa.JSON(), nullable=False),
        sa.Column("findings", sa.Text(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_run_started_at"), ["started_at"], unique=False)

    op.create_table(
        "news_cluster",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("relevance", sa.String(), nullable=False),
        sa.Column("max_impact", sa.Integer(), nullable=True),
        sa.Column("linked", sa.Boolean(), nullable=False),
        sa.Column("assessed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_cluster", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_cluster_first_seen"), ["first_seen"], unique=False
        )

    op.create_table(
        "news_source",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("trust_weight", sa.String(), nullable=False),
        sa.Column("poll_minutes", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("macro_series", sa.JSON(), nullable=False),
        sa.Column("etag", sa.String(length=200), nullable=True),
        sa.Column("last_modified", sa.String(length=100), nullable=True),
        sa.Column("last_fetch_at", sa.DateTime(), nullable=True),
        sa.Column("next_fetch_at", sa.DateTime(), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news_assessment",
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("impact_score", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("horizon", sa.String(length=12), nullable=False),
        sa.Column("affected", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=6), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("cost_eur", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_cluster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_assessment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_assessment_cluster_id"), ["cluster_id"], unique=False
        )

    op.create_table(
        "news_feedback",
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.String(length=12), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_cluster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["news_source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_feedback_cluster_id"), ["cluster_id"], unique=False
        )

    op.create_table(
        "news_item",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("canonical_url", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_cluster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["news_source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url"),
    )
    with op.batch_alter_table("news_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_news_item_cluster_id"), ["cluster_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_news_item_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_news_item_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_item_source_id"), ["source_id"], unique=False)

    op.create_table(
        "calculation",
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("strategy_version_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "etf_snapshot",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("covered_pct", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "as_of", "source"),
    )
    with op.batch_alter_table("etf_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_etf_snapshot_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "instrument_alias",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("weight", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "alias"),
    )
    with op.batch_alter_table("instrument_alias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_instrument_alias_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "news_link",
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("sleeve", sa.String(length=100), nullable=True),
        sa.Column("link_type", sa.String(length=12), nullable=False),
        sa.Column("weight_pct", sa.String(), nullable=True),
        sa.Column("relevance", sa.String(), nullable=False),
        sa.Column("matched_by", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_cluster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_link", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_news_link_cluster_id"), ["cluster_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_news_link_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "etf_constituent",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(length=30), nullable=True),
        sa.Column("weight_pct", sa.String(), nullable=False),
        sa.Column("sector", sa.String(length=60), nullable=True),
        sa.Column("country", sa.String(length=60), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["etf_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("etf_constituent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_etf_constituent_isin"), ["isin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_etf_constituent_snapshot_id"), ["snapshot_id"], unique=False
        )

    op.create_table(
        "recommendation",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("subjects", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("calculation_id", sa.Integer(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.String(length=6), nullable=False),
        sa.Column("departs_from_principles", sa.Text(), nullable=True),
        sa.Column("what_would_change_this", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("refused_reason", sa.Text(), nullable=True),
        sa.Column("user_note", sa.String(length=300), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(), nullable=True),
        sa.Column("linked_transaction_ids", sa.JSON(), nullable=False),
        sa.Column("price_at_creation", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calculation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recommendation_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendation_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_status"))
        batch_op.drop_index(batch_op.f("ix_recommendation_run_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_expires_at"))

    op.drop_table("recommendation")
    with op.batch_alter_table("etf_constituent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_etf_constituent_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_etf_constituent_isin"))

    op.drop_table("etf_constituent")
    with op.batch_alter_table("news_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_link_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_news_link_cluster_id"))

    op.drop_table("news_link")
    with op.batch_alter_table("instrument_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instrument_alias_instrument_id"))

    op.drop_table("instrument_alias")
    with op.batch_alter_table("etf_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_etf_snapshot_instrument_id"))

    op.drop_table("etf_snapshot")
    op.drop_table("calculation")
    with op.batch_alter_table("news_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_item_source_id"))
        batch_op.drop_index(batch_op.f("ix_news_item_published_at"))
        batch_op.drop_index(batch_op.f("ix_news_item_content_hash"))
        batch_op.drop_index(batch_op.f("ix_news_item_cluster_id"))

    op.drop_table("news_item")
    with op.batch_alter_table("news_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_feedback_cluster_id"))

    op.drop_table("news_feedback")
    with op.batch_alter_table("news_assessment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_assessment_cluster_id"))

    op.drop_table("news_assessment")
    op.drop_table("news_source")
    with op.batch_alter_table("news_cluster", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_cluster_first_seen"))

    op.drop_table("news_cluster")
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_run_started_at"))

    op.drop_table("agent_run")
    # ### end Alembic commands ###
