"""news item symbols

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05 18:38:25.898832
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("symbols", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_item", schema=None) as batch_op:
        batch_op.drop_column("symbols")

    # ### end Alembic commands ###
